// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	SignUp(ctx context.Context, in *SignUpReq, opts ...client.CallOption) (*SignUpResp, error)
	SignIn(ctx context.Context, in *SignInReq, opts ...client.CallOption) (*SignInResp, error)
	GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...client.CallOption) (*UserInfoResp, error)
	GetUserFiles(ctx context.Context, in *UserFilesReq, opts ...client.CallOption) (*UserFilesResp, error)
	RenameUserFile(ctx context.Context, in *RenameUserFileReq, opts ...client.CallOption) (*RenameUserFileResp, error)
	DeleteUserFile(ctx context.Context, in *DeleteUserFileReq, opts ...client.CallOption) (*DeleteUserFileResp, error)
	DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...client.CallOption) (*DeleteFileResp, error)
	DeleteUserFileAndUniqueFile(ctx context.Context, in *DeleteAllReq, opts ...client.CallOption) (*DeleteAllResp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) SignUp(ctx context.Context, in *SignUpReq, opts ...client.CallOption) (*SignUpResp, error) {
	req := c.c.NewRequest(c.name, "UserService.SignUp", in)
	out := new(SignUpResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SignIn(ctx context.Context, in *SignInReq, opts ...client.CallOption) (*SignInResp, error) {
	req := c.c.NewRequest(c.name, "UserService.SignIn", in)
	out := new(SignInResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...client.CallOption) (*UserInfoResp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserInfo", in)
	out := new(UserInfoResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserFiles(ctx context.Context, in *UserFilesReq, opts ...client.CallOption) (*UserFilesResp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserFiles", in)
	out := new(UserFilesResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) RenameUserFile(ctx context.Context, in *RenameUserFileReq, opts ...client.CallOption) (*RenameUserFileResp, error) {
	req := c.c.NewRequest(c.name, "UserService.RenameUserFile", in)
	out := new(RenameUserFileResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeleteUserFile(ctx context.Context, in *DeleteUserFileReq, opts ...client.CallOption) (*DeleteUserFileResp, error) {
	req := c.c.NewRequest(c.name, "UserService.DeleteUserFile", in)
	out := new(DeleteUserFileResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...client.CallOption) (*DeleteFileResp, error) {
	req := c.c.NewRequest(c.name, "UserService.DeleteFile", in)
	out := new(DeleteFileResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeleteUserFileAndUniqueFile(ctx context.Context, in *DeleteAllReq, opts ...client.CallOption) (*DeleteAllResp, error) {
	req := c.c.NewRequest(c.name, "UserService.DeleteUserFileAndUniqueFile", in)
	out := new(DeleteAllResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	SignUp(context.Context, *SignUpReq, *SignUpResp) error
	SignIn(context.Context, *SignInReq, *SignInResp) error
	GetUserInfo(context.Context, *UserInfoReq, *UserInfoResp) error
	GetUserFiles(context.Context, *UserFilesReq, *UserFilesResp) error
	RenameUserFile(context.Context, *RenameUserFileReq, *RenameUserFileResp) error
	DeleteUserFile(context.Context, *DeleteUserFileReq, *DeleteUserFileResp) error
	DeleteFile(context.Context, *DeleteFileReq, *DeleteFileResp) error
	DeleteUserFileAndUniqueFile(context.Context, *DeleteAllReq, *DeleteAllResp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		SignUp(ctx context.Context, in *SignUpReq, out *SignUpResp) error
		SignIn(ctx context.Context, in *SignInReq, out *SignInResp) error
		GetUserInfo(ctx context.Context, in *UserInfoReq, out *UserInfoResp) error
		GetUserFiles(ctx context.Context, in *UserFilesReq, out *UserFilesResp) error
		RenameUserFile(ctx context.Context, in *RenameUserFileReq, out *RenameUserFileResp) error
		DeleteUserFile(ctx context.Context, in *DeleteUserFileReq, out *DeleteUserFileResp) error
		DeleteFile(ctx context.Context, in *DeleteFileReq, out *DeleteFileResp) error
		DeleteUserFileAndUniqueFile(ctx context.Context, in *DeleteAllReq, out *DeleteAllResp) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) SignUp(ctx context.Context, in *SignUpReq, out *SignUpResp) error {
	return h.UserServiceHandler.SignUp(ctx, in, out)
}

func (h *userServiceHandler) SignIn(ctx context.Context, in *SignInReq, out *SignInResp) error {
	return h.UserServiceHandler.SignIn(ctx, in, out)
}

func (h *userServiceHandler) GetUserInfo(ctx context.Context, in *UserInfoReq, out *UserInfoResp) error {
	return h.UserServiceHandler.GetUserInfo(ctx, in, out)
}

func (h *userServiceHandler) GetUserFiles(ctx context.Context, in *UserFilesReq, out *UserFilesResp) error {
	return h.UserServiceHandler.GetUserFiles(ctx, in, out)
}

func (h *userServiceHandler) RenameUserFile(ctx context.Context, in *RenameUserFileReq, out *RenameUserFileResp) error {
	return h.UserServiceHandler.RenameUserFile(ctx, in, out)
}

func (h *userServiceHandler) DeleteUserFile(ctx context.Context, in *DeleteUserFileReq, out *DeleteUserFileResp) error {
	return h.UserServiceHandler.DeleteUserFile(ctx, in, out)
}

func (h *userServiceHandler) DeleteFile(ctx context.Context, in *DeleteFileReq, out *DeleteFileResp) error {
	return h.UserServiceHandler.DeleteFile(ctx, in, out)
}

func (h *userServiceHandler) DeleteUserFileAndUniqueFile(ctx context.Context, in *DeleteAllReq, out *DeleteAllResp) error {
	return h.UserServiceHandler.DeleteUserFileAndUniqueFile(ctx, in, out)
}
